import type { CreatureTemplate } from '@/shared/types';

import { imageConfig } from '../config/image-config';
import { initModifier } from '../utils';

export const creatureKeyValues = [
  'PIG',
  'SHEEP',
  'CHICKEN',
  'RAT',
  'RABBIT',
  'DEER',
  'BUTTERFLY',
  'WILD_DOG',
  'COW',
  'BULL',
  'LIZARD',
  'SCORPION',
  'BOAR',
  'FOX',
  'WOLF',
  'BEAR',
  'BAT',
  'MOUNTAIN_GOAT',
  'HARPY',
  'ROCK_TROLL',
  'SNAKE',
  'SPIDER',
  'GOBLIN_SCOUT',
  'CROW',
  'FROG',
  'DUCK',
  'OTTER',
] as const;

export type CreatureKey = (typeof creatureKeyValues)[number];

export const creatureTemplate = [
  // FARM
  {
    id: '019cf851-85f4-76bd-ae12-be9e1f2808ac',
    type: 'ANIMAL',
    name: 'pig',
    key: 'PIG',
    scale: 1,
    image: imageConfig.creature.PIG,
    isAggressive: false,
    currentHealth: 100,
    maxHealth: 100,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 5,
      dexterity: 3,
      constitution: 10,
      luck: 2,
      maxHealth: 100,
      minDamage: 2,
      maxDamage: 4,
      armor: 2,
      evasion: 2,
      physCritRating: 2,
      physHitRating: 60,
    }),
  },
  {
    id: '019defd0-2c13-76b6-8f9f-cc8da838661f',
    type: 'ANIMAL',
    name: 'chicken',
    key: 'CHICKEN',
    scale: 0.6,
    image: imageConfig.creature.CHICKEN,
    isAggressive: false,
    currentHealth: 30,
    maxHealth: 30,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 1,
      dexterity: 8,
      constitution: 3,
      luck: 3,
      maxHealth: 30,
      minDamage: 1,
      maxDamage: 2,
      evasion: 8,
    }),
  },
  {
    id: '019cf870-846f-7a9f-beee-ee2628d7f053',
    type: 'ANIMAL',
    name: 'sheep',
    scale: 1,
    key: 'SHEEP',
    image: imageConfig.creature.SHEEP,
    isAggressive: false,
    currentHealth: 70,
    maxHealth: 70,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 4,
      dexterity: 7,
      constitution: 7,
      luck: 2,
      maxHealth: 70,
      minDamage: 1,
      maxDamage: 3,
      armor: 1,
      evasion: 5,
      physCritRating: 1,
      physHitRating: 55,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000001',
    type: 'ANIMAL',
    name: 'cow',
    scale: 1,
    key: 'COW',
    image: imageConfig.creature.COW,
    isAggressive: false,
    currentHealth: 150,
    maxHealth: 150,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 8,
      dexterity: 2,
      constitution: 15,
      luck: 1,
      maxHealth: 150,
      minDamage: 2,
      maxDamage: 5,
      armor: 3,
      evasion: 1,
      physCritRating: 2,
      physHitRating: 55,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000002',
    type: 'ANIMAL',
    name: 'bull',
    scale: 1,
    key: 'BULL',
    image: imageConfig.creature.BULL,
    isAggressive: true,
    currentHealth: 200,
    maxHealth: 200,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 18,
      dexterity: 5,
      constitution: 20,
      luck: 1,
      maxHealth: 200,
      minDamage: 10,
      maxDamage: 18,
      armor: 6,
      evasion: 2,
      physCritDamage: 15,
      physCritRating: 5,
      physHitRating: 65,
      physPenetration: 2,
    }),
  },

  // MEADOW / PLAINS
  {
    id: '019cf871-0001-7000-b000-000000000003',
    type: 'ANIMAL',
    name: 'rabbit',
    scale: 0.6,
    key: 'RABBIT',
    image: imageConfig.creature.RABBIT,
    isAggressive: false,
    currentHealth: 30,
    maxHealth: 30,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 2,
      dexterity: 18,
      constitution: 3,
      luck: 5,
      maxHealth: 30,
      minDamage: 1,
      maxDamage: 2,
      evasion: 15,
      physHitRating: 45,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000004',
    type: 'ANIMAL',
    name: 'deer',
    scale: 1,
    key: 'DEER',
    image: imageConfig.creature.DEER,
    isAggressive: false,
    currentHealth: 80,
    maxHealth: 80,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 6,
      dexterity: 15,
      constitution: 8,
      luck: 3,
      maxHealth: 80,
      minDamage: 2,
      maxDamage: 5,
      armor: 1,
      evasion: 12,
      physCritRating: 2,
      physHitRating: 55,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000005',
    type: 'INSECT',
    name: 'butterfly',
    scale: 1,
    key: 'BUTTERFLY',
    image: imageConfig.creature.BUTTERFLY,
    isAggressive: false,
    currentHealth: 10,
    maxHealth: 10,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      dexterity: 20,
      luck: 8,
      maxHealth: 10,
      minDamage: 0,
      maxDamage: 1,
      evasion: 20,
      physHitRating: 30,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000006',
    type: 'BEAST',
    name: 'wild_dog',
    key: 'WILD_DOG',
    scale: 1,
    image: imageConfig.creature.WILD_DOG,
    isAggressive: true,
    currentHealth: 90,
    maxHealth: 90,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 12,
      dexterity: 14,
      constitution: 9,
      luck: 3,
      maxHealth: 90,
      minDamage: 6,
      maxDamage: 12,
      armor: 2,
      evasion: 10,
      physCritDamage: 10,
      physCritRating: 5,
      physHitRating: 70,
      physPenetration: 1,
    }),
  },

  // ROCKY_FIELD
  {
    id: '019cf871-0001-7000-b000-000000000007',
    type: 'REPTILE',
    name: 'lizard',
    key: 'LIZARD',
    scale: 1,
    image: imageConfig.creature.LIZARD,
    isAggressive: false,
    currentHealth: 60,
    maxHealth: 60,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 8,
      dexterity: 12,
      constitution: 6,
      luck: 2,
      maxHealth: 60,
      minDamage: 3,
      maxDamage: 7,
      armor: 3,
      magicResistance: 1,
      evasion: 8,
      physCritRating: 3,
      physHitRating: 65,
      physPenetration: 1,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000008',
    type: 'INSECT',
    name: 'scorpion',
    key: 'SCORPION',
    scale: 1,
    image: imageConfig.creature.SCORPION,
    isAggressive: true,
    currentHealth: 80,
    maxHealth: 80,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 14,
      dexterity: 10,
      constitution: 8,
      luck: 2,
      maxHealth: 80,
      minDamage: 8,
      maxDamage: 14,
      armor: 5,
      magicResistance: 2,
      evasion: 6,
      physCritDamage: 10,
      physCritRating: 5,
      physHitRating: 65,
      physPenetration: 2,
    }),
  },
  {
    id: '019cf871-0002-7000-b000-000000000005',
    type: 'REPTILE',
    name: 'snake',
    key: 'SNAKE',
    scale: 0.8,
    image: imageConfig.creature.SNAKE,
    isAggressive: true,
    currentHealth: 70,
    maxHealth: 70,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 10,
      dexterity: 16,
      constitution: 7,
      luck: 2,
      maxHealth: 70,
      minDamage: 7,
      maxDamage: 13,
      armor: 2,
      magicResistance: 3,
      evasion: 12,
      physCritDamage: 15,
      physCritRating: 8,
      physHitRating: 70,
      physPenetration: 2,
    }),
  },
  {
    id: '019cf871-0002-7000-b000-000000000006',
    type: 'INSECT',
    name: 'spider',
    key: 'SPIDER',
    scale: 1,
    image: imageConfig.creature.SPIDER,
    isAggressive: true,
    currentHealth: 60,
    maxHealth: 60,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 8,
      dexterity: 18,
      constitution: 6,
      luck: 3,
      maxHealth: 60,
      minDamage: 5,
      maxDamage: 10,
      armor: 2,
      magicResistance: 2,
      evasion: 14,
      physCritDamage: 10,
      physCritRating: 6,
      physHitRating: 68,
      physPenetration: 1,
    }),
  },
  {
    id: '019cf871-0002-7000-b000-000000000007',
    type: 'HUMANOID',
    name: 'goblin_scout',
    key: 'GOBLIN_SCOUT',
    scale: 1,
    image: imageConfig.creature.GOBLIN_SCOUT,
    isAggressive: true,
    currentHealth: 100,
    maxHealth: 100,
    currentMana: 20,
    maxMana: 20,
    modifier: initModifier({
      strength: 12,
      dexterity: 15,
      intelligence: 6,
      wisdom: 4,
      constitution: 10,
      luck: 4,
      maxHealth: 100,
      maxMana: 20,
      minDamage: 8,
      maxDamage: 14,
      armor: 4,
      magicResistance: 3,
      evasion: 10,
      physCritDamage: 12,
      physCritRating: 6,
      physHitRating: 72,
      physPenetration: 2,
    }),
  },

  // FOREST / DENSE_FOREST
  {
    id: '019cf871-0001-7000-b000-000000000009',
    type: 'BEAST',
    name: 'boar',
    key: 'BOAR',
    scale: 1,
    image: imageConfig.creature.BOAR,
    isAggressive: false,
    currentHealth: 120,
    maxHealth: 120,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 14,
      dexterity: 8,
      constitution: 12,
      luck: 2,
      maxHealth: 120,
      minDamage: 6,
      maxDamage: 12,
      armor: 4,
      evasion: 4,
      physCritDamage: 10,
      physCritRating: 4,
      physHitRating: 65,
      physPenetration: 2,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000010',
    type: 'BEAST',
    name: 'fox',
    key: 'FOX',
    scale: 1,
    image: imageConfig.creature.FOX,
    isAggressive: false,
    currentHealth: 70,
    maxHealth: 70,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 8,
      dexterity: 16,
      constitution: 7,
      luck: 5,
      maxHealth: 70,
      minDamage: 4,
      maxDamage: 8,
      armor: 1,
      evasion: 13,
      physCritDamage: 8,
      physCritRating: 4,
      physHitRating: 68,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000011',
    type: 'BEAST',
    name: 'wolf',
    key: 'WOLF',
    scale: 1,
    image: imageConfig.creature.WOLF,
    isAggressive: true,
    currentHealth: 140,
    maxHealth: 140,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 16,
      dexterity: 14,
      constitution: 14,
      luck: 3,
      maxHealth: 140,
      minDamage: 10,
      maxDamage: 18,
      armor: 5,
      evasion: 10,
      physCritDamage: 15,
      physCritRating: 8,
      physHitRating: 75,
      physPenetration: 3,
    }),
  },
  {
    id: '019d062f-79e2-7054-b6e9-c823838415c9',
    type: 'BEAST',
    name: 'rat',
    key: 'RAT',
    scale: 0.7,
    image: imageConfig.creature.RAT,
    isAggressive: true,
    currentHealth: 50,
    maxHealth: 50,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 6,
      dexterity: 14,
      constitution: 5,
      luck: 3,
      maxHealth: 50,
      minDamage: 3,
      maxDamage: 7,
      evasion: 11,
      physCritDamage: 8,
      physCritRating: 4,
      physHitRating: 65,
    }),
  },
  {
    id: '019cf871-0001-7000-b000-000000000012',
    type: 'BEAST',
    name: 'bear',
    key: 'BEAR',
    scale: 1,
    image: imageConfig.creature.BEAR,
    isAggressive: true,
    currentHealth: 250,
    maxHealth: 250,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 22,
      dexterity: 6,
      constitution: 25,
      luck: 2,
      maxHealth: 250,
      minDamage: 16,
      maxDamage: 26,
      armor: 10,
      magicResistance: 3,
      evasion: 3,
      physCritDamage: 20,
      physCritRating: 6,
      physHitRating: 68,
      physPenetration: 5,
    }),
  },

  // CAVE
  {
    id: '019cf871-0002-7000-b000-000000000004',
    type: 'BEAST',
    name: 'bat',
    key: 'BAT',
    scale: 0.9,
    image: imageConfig.creature.BAT,
    isAggressive: true,
    currentHealth: 40,
    maxHealth: 40,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 6,
      dexterity: 20,
      constitution: 4,
      luck: 3,
      maxHealth: 40,
      minDamage: 3,
      maxDamage: 6,
      evasion: 18,
      physCritRating: 5,
      physHitRating: 70,
    }),
  },

  // MOUNTAIN
  {
    id: '019cf871-0002-7000-b000-000000000001',
    type: 'ANIMAL',
    name: 'mountain_goat',
    key: 'MOUNTAIN_GOAT',
    scale: 1,
    image: imageConfig.creature.MOUNTAIN_GOAT,
    isAggressive: false,
    currentHealth: 90,
    maxHealth: 90,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 10,
      dexterity: 12,
      constitution: 10,
      luck: 3,
      maxHealth: 90,
      minDamage: 3,
      maxDamage: 7,
      armor: 3,
      evasion: 9,
      physCritRating: 3,
      physHitRating: 62,
      physPenetration: 1,
    }),
  },
  {
    id: '019cf871-0002-7000-b000-000000000002',
    type: 'BEAST',
    name: 'harpy',
    key: 'HARPY',
    scale: 1,
    image: imageConfig.creature.HARPY,
    isAggressive: true,
    currentHealth: 160,
    maxHealth: 160,
    currentMana: 30,
    maxMana: 30,
    modifier: initModifier({
      strength: 16,
      dexterity: 18,
      intelligence: 8,
      wisdom: 5,
      constitution: 12,
      luck: 4,
      maxHealth: 160,
      maxMana: 30,
      minDamage: 12,
      maxDamage: 20,
      armor: 6,
      magicResistance: 8,
      evasion: 14,
      spellDamage: 5,
      spellCritDamage: 10,
      spellCritRating: 5,
      spellHitRating: 60,
      spellPenetration: 2,
      physCritDamage: 15,
      physCritRating: 8,
      physHitRating: 75,
      physPenetration: 3,
    }),
  },
  {
    id: '019cf871-0002-7000-b000-000000000003',
    type: 'GIANT',
    name: 'rock_troll',
    key: 'ROCK_TROLL',
    scale: 1,
    image: imageConfig.creature.ROCK_TROLL,
    isAggressive: true,
    currentHealth: 300,
    maxHealth: 300,
    currentMana: 0,
    maxMana: 0,
    modifier: initModifier({
      strength: 24,
      dexterity: 4,
      constitution: 28,
      luck: 1,
      maxHealth: 300,
      minDamage: 20,
      maxDamage: 35,
      armor: 18,
      magicResistance: 5,
      evasion: 1,
      physCritDamage: 25,
      physCritRating: 5,
      physHitRating: 60,
      physPenetration: 8,
    }),
  },
] as const satisfies CreatureTemplate[];

export const creatureTemplateById = creatureTemplate.reduce(
  (acc, c) => {
    acc[c.id] = c;
    return acc;
  },
  {} as Record<string, CreatureTemplate>,
);
export const creatureTemplateByKey = creatureTemplate.reduce(
  (acc, c) => {
    acc[c.key] = c;
    return acc;
  },
  {} as Record<CreatureKey, CreatureTemplate>,
);
