# fly.toml app configuration file generated for good-news-app on 2025-04-08T15:36:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'good-news-app'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[[env]]
PORT = "3000"
DATABASE_URL="postgresql://neondb_owner:npg_7nUrBFx0RQAO@ep-weathered-violet-a2l1xcgo-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
BREVO_USERNAME="8a9cd7001@smtp-brevo.com"
BREVO_PASS="JmO7EKrFj9HUfWan"
JWT_SECRET="v0TXiKbeo3LREC3"
BASE_URL_FRONT="good-news.space"
