import type { SkillKey } from '../templates/skill-template';
import type { ArmorType, FishType, IHeroStat, ResourceType, StateType, WeaponType } from '../types';

export const imageConfig = {
  icon: {
    ui: {
      fish: '/sprites/icons/ui/fish.png',
      back: '/sprites/icons/ui/back.png',
      gold: '/sprites/icons/ui/gold.png',
      prem: '/sprites/icons/ui/prem.png',
      group: '/sprites/icons/ui/group.png',
      logo: '/sprites/icons/ui/logo.png',
      map: '/sprites/icons/ui/map.png',
      random: '/sprites/icons/ui/random.png',
      town: '/sprites/icons/ui/town.png',
      dungeon: '/sprites/icons/ui/dungeon.png',
      leave: '/sprites/icons/ui/leave.png',
      backpack: '/sprites/icons/ui/backpack.png',
      bag: '/sprites/icons/ui/bag.png',
      chest: '/sprites/icons/ui/chest.png',
      chest2: '/sprites/icons/ui/chest2.png',
      chest3: '/sprites/icons/ui/chest3.png',
      battle: '/sprites/icons/ui/battle.png',
      book: '/sprites/icons/ui/book.png',
      defense: '/sprites/icons/ui/defense.png',
      'magic-resistance': '/sprites/icons/ui/defense.png',
      fire: '/sprites/icons/ui/fire.png',
      grave: '/sprites/icons/ui/grave.png',
      hammer: '/sprites/icons/ui/hammer.png',
      pick: '/sprites/icons/ui/pick.png',
      skull: '/sprites/icons/ui/skull.png',
      walk: '/sprites/icons/ui/walk.png',
      refresh: '/sprites/icons/ui/refresh.png',
      settings: '/sprites/icons/ui/settings.png',
      skill: '/sprites/icons/ui/skill.png',
      gold2: '/sprites/icons/ui/gold2.png',
      'gold-bag': '/sprites/icons/ui/gold-bag.png',
      bag2: '/sprites/icons/ui/bag2.png',
      bag3: '/sprites/icons/ui/bag3.png',
      'shop-cart': '/sprites/icons/ui/shop-cart.png',
      buy: '/sprites/icons/ui/buy.png',
      sell: '/sprites/icons/ui/sell.png',
      character: '/sprites/icons/ui/character.png',
      refine: '/sprites/icons/ui/refine.png',
    },
    action: {
      close: '/sprites/icons/action/close.png',
      equip: '/sprites/icons/action/equip.png',
      unEquip: '/sprites/icons/action/unEquip.png',
      drink: '/sprites/icons/action/drink.png',
      read: '/sprites/icons/action/read.png',
    },
    stat: {
      strength: '/sprites/icons/stats/strength.png',
      dexterity: '/sprites/icons/stats/dexterity.png',
      intelligence: '/sprites/icons/stats/intelligence.png',
      wisdom: '/sprites/icons/stats/wisdom.png',
      constitution: '/sprites/icons/stats/constitution.png',
      luck: '/sprites/icons/stats/luck.png',
    } as Record<keyof IHeroStat, string>,
    state: {
      IDLE: '/sprites/icons/state/idle.png',
      BATTLE: '/sprites/icons/state/battle.png',
      WALK: '/sprites/icons/state/walk.png',
      BLACKSMITHING: '/sprites/icons/skills/blacksmithing.png',
      ALCHEMY: '/sprites/icons/skills/alchemy.png',
      TAILORING: '/sprites/icons/skills/tailoring.png',
      CARPENTRY: '/sprites/icons/skills/carpentry.png',
      SMELTING: '/sprites/icons/skills/smelting.png',
      TANNING: '/sprites/icons/skills/tanning.png',
      WEAVING: '/sprites/icons/skills/weaving.png',
      SAWMILLING: '/sprites/icons/skills/sawmilling.png',
      MINING: '/sprites/icons/skills/mining.png',
      WOODCUTTING: '/sprites/icons/skills/woodcutting.png',
      FISHING: '/sprites/icons/skills/fishing.png',
      SKINNING: '/sprites/icons/skills/skinning.png',
      FORAGING: '/sprites/icons/skills/herbalism.png',
    } as Record<StateType, string>,
    skill: {
      BLACKSMITHING: '/sprites/icons/skills/blacksmithing.png',
      ALCHEMY: '/sprites/icons/skills/alchemy.png',
      TAILORING: '/sprites/icons/skills/tailoring.png',
      CARPENTRY: '/sprites/icons/skills/carpentry.png',
      SMELTING: '/sprites/icons/skills/smelting.png',
      TANNING: '/sprites/icons/skills/tanning.png',
      WEAVING: '/sprites/icons/skills/weaving.png',
      SAWMILLING: '/sprites/icons/skills/sawmilling.png',
      MINING: '/sprites/icons/skills/mining.png',
      WOODCUTTING: '/sprites/icons/skills/woodcutting.png',
      FISHING: '/sprites/icons/skills/fishing.png',
      SKINNING: '/sprites/icons/skills/skinning.png',
      FORAGING: '/sprites/icons/skills/foraging.png',
      ORE_LORE: '/sprites/icons/skills/ore-lore.png',
      METAL_LORE: '/sprites/icons/skills/metal-lore.png',
      HIDE_LORE: '/sprites/icons/skills/hide-lore.png',
      LEATHER_LORE: '/sprites/icons/skills/leather-lore.png',
      FUR_LORE: '/sprites/icons/skills/fur-lore.png',
      CURED_FUR_LORE: '/sprites/icons/skills/cured-fur-lore.png',
      WOOD_LORE: '/sprites/icons/skills/wood-lore.png',
      HERB_LORE: '/sprites/icons/skills/herb-lore.png',
      FLOWER_LORE: '/sprites/icons/skills/flower-lore.png',
      MUSHROOM_LORE: '/sprites/icons/skills/mushroom-lore.png',
      FIBER_LORE: '/sprites/icons/skills/fiber-lore.png',
      CLOTH_LORE: '/sprites/icons/skills/cloth-lore.png',
      BONE_LORE: '/sprites/icons/skills/bone-lore.png',
      REGENERATION: '/sprites/icons/skills/regeneration.png',
      MEDITATION: '/sprites/icons/skills/meditation.png',
    } as Record<SkillKey, string>,
    place: {
      mine: '/sprites/icons/places/mine.png',
      solmer: '/sprites/icons/places/solmer.webp',
    },
    building: {
      blacksmith: '/sprites/icons/buildings/blacksmith.png',
      alchemy: '/sprites/icons/buildings/alchemy.png',
      tailor: '/sprites/icons/buildings/tailor.png',
      carpenter: '/sprites/icons/buildings/carpenter.png',

      forge: '/sprites/icons/buildings/forge.png',
      tannery: '/sprites/icons/buildings/tannery.png',
      sawmill: '/sprites/icons/buildings/sawmill.png',
      loom: '/sprites/icons/buildings/loom.png',

      temple: '/sprites/icons/buildings/temple.png',
    },
    entrance: {
      portal: '/sprites/icons/entrance/portal.png',
      mine: '/sprites/icons/entrance/mine.png',
    },
    book: {
      'unlock-skill': '/sprites/icons/books/unlock-skill.png',
      'train-skill': '/sprites/icons/books/train-skill.png',
    },
    WEAPON: {
      SWORD: '/sprites/icons/weapon/sword.png',
      AXE: '/sprites/icons/weapon/axe.png',
      DAGGER: '/sprites/icons/weapon/dagger.png',
      STAFF: '/sprites/icons/weapon/staff.png',
    } as Record<WeaponType, string>,
    ARMOR: {
      BOOTS: '/sprites/icons/armor/boots.png',
      BELT: '/sprites/icons/armor/belt.png',
      CHEST: '/sprites/icons/armor/chest.png',
      GLOVES: '/sprites/icons/armor/gloves.png',
      HELMET: '/sprites/icons/armor/helmet.png',
      SHIELD: '/sprites/icons/armor/shield.png',
    } as Record<ArmorType, string>,
    ACCESSORY: {
      AMULET: '/sprites/icons/accessory/amulet.png',
      RING: '/sprites/icons/accessory/ring.png',
    },

    POTION: {
      buff: {
        strength: '/sprites/icons/potions/str.png',
        constitution: '/sprites/icons/potions/const.png',
        intelligence: '/sprites/icons/potions/int.png',
        wisdom: '/sprites/icons/potions/wis.png',
        dexterity: '/sprites/icons/potions/dex.png',
        luck: '/sprites/icons/potions/luck.png',
      },
      restore: {
        smallHealth: '/sprites/icons/potions/small-health.png',
        smallMana: '/sprites/icons/potions/small-mana.png',
        smallRestore: '/sprites/icons/potions/small-restore.png',
        mediumHealth: '/sprites/icons/potions/medium-health.png',
        mediumMana: '/sprites/icons/potions/medium-mana.png',
        mediumRestore: '/sprites/icons/potions/medium-restore.png',
      },
    },
    RESOURCES: {
      LOG: '/sprites/icons/resources/log.png',
      PLANK: '/sprites/icons/resources/plank.png',
      ORE: '/sprites/icons/resources/ore.png',
      INGOT: '/sprites/icons/resources/ingot.png',
      HIDE: '/sprites/icons/resources/hide.png',
      LEATHER: '/sprites/icons/resources/leather.png',
      FIBER: '/sprites/icons/resources/fiber.png',
      CLOTH: '/sprites/icons/resources/cloth.png',
      FUR: '/sprites/icons/resources/fur.png',
      CURED_FUR: '/sprites/icons/resources/cured-fur.png',
      BONE: '/sprites/icons/resources/bone.png',
      FLAX: '/sprites/icons/resources/flax.png',
      COTTON: '/sprites/icons/resources/cotton.png',
      flowers: {
        ROSE: '/sprites/icons/resources/flowers/rose.png',
        SUNFLOWER: '/sprites/icons/resources/flowers/sunflower.png',
        BLUE_ORCHID: '/sprites/icons/resources/flowers/blueorchid.png',
        NIGHT_BLOOM: '/sprites/icons/resources/flowers/nightbloom.png',
        FIRE_BLOSSOM: '/sprites/icons/resources/flowers/fireblossom.png',
        FROST_LILY: '/sprites/icons/resources/flowers/frostlily.png',
      },
      mushrooms: {
        REDCAP_MUSHROOM: '/sprites/icons/resources/mushrooms/redcap.png',
        GLOWCAP_MUSHROOM: '/sprites/icons/resources/mushrooms/glowcap.png',
        SHADOWCAP_MUSHROOM: '/sprites/icons/resources/mushrooms/shadowcap.png',
        SPORECAP_MUSHROOM: '/sprites/icons/resources/mushrooms/sporecap.png',
        IRONCAP_MUSHROOM: '/sprites/icons/resources/mushrooms/ironcap.png',
        FROSTCAP_MUSHROOM: '/sprites/icons/resources/mushrooms/frostcap.png',
      },
      herbs: {
        GREENLEAF: '/sprites/icons/resources/herbs/greenleaf.png',
        SWIFTLEAF: '/sprites/icons/resources/herbs/swiftleaf.png',
        BITTERROOT: '/sprites/icons/resources/herbs/bitterroot.png',
        SUNGRASS: '/sprites/icons/resources/herbs/sungrass.png',
        GHOST_HERB: '/sprites/icons/resources/herbs/ghostherb.png',
        BLOOD_HERB: '/sprites/icons/resources/herbs/bloodherb.png',
        JASMINE: '/sprites/icons/resources/herbs/jasmine.png',
      },
    },
    FOOD: {
      fish: {
        TUNA: '/sprites/icons/food/fish/tuna.png',
        SQUID: '/sprites/icons/food/fish/squid.png',
        SMALL_FISH: '/sprites/icons/food/fish/small-fish.png',
        SHARK: '/sprites/icons/food/fish/shark.png',
        SALMON: '/sprites/icons/food/fish/salmon.png',
        PUFFERFISH: '/sprites/icons/food/fish/pufferfish.png',
        PERCH: '/sprites/icons/food/fish/perch.png',
        JELLYFISH: '/sprites/icons/food/fish/jellyfish.png',
        CATFISH: '/sprites/icons/food/fish/catfish.png',
        CARP: '/sprites/icons/food/fish/carp.png',
        ANGLERFISH: '/sprites/icons/food/fish/anglerfish.png',
      } as Record<FishType, string>,
    },
  },
  bg: {
    shrine: '/sprites/bg/shrine.png',
    map: {
      SolmereValley: '/sprites/bg/map/solmer-valley.png',
      solmerMine: '/sprites/bg/map/solmer-mine.png',
    },
  },
  creature: {
    animal: {
      pig: '/sprites/creatures/animals/pig.png',
      sheep: '/sprites/creatures/animals/sheep.png',
    },
    beast: {
      rat: '/sprites/creatures/beasts/rat.png',
      bat: '/sprites/creatures/beasts/bat.png',
    },
  },
  npc: {
    vex: '/sprites/npc/vex.png',
    aldric: '/sprites/npc/aldric.png',
    brom: '/sprites/npc/brom.png',
    lyra: '/sprites/npc/lyra.png',
    maria: '/sprites/npc/maria.png',
    deus: '/sprites/npc/deus.png',
  },
  equipments: {
    tools: {
      'blacksmith-hammer': '/sprites/equipments/tools/blacksmith-hammer.png',
      'fishing-rod': '/sprites/equipments/tools/fishing-rod.png',
      'lumber-axe': '/sprites/equipments/tools/lumber-axe.png',
      'mining-pickaxe': '/sprites/equipments/tools/mining-pickaxe.png',
    },
  },
} as const;
