/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as homeRouteImport } from './routes/(home)/route'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as homeIndexImport } from './routes/(home)/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AuthConfirmEmailImport } from './routes/auth/confirm-email'
import { Route as homeAboutImport } from './routes/(home)/about'
import { Route as homePostPostIdImport } from './routes/(home)/post/$postId'

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const homeRouteRoute = homeRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const homeIndexRoute = homeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthConfirmEmailRoute = AuthConfirmEmailImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRouteRoute,
} as any)

const homeAboutRoute = homeAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => homeRouteRoute,
} as any)

const homePostPostIdRoute = homePostPostIdImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => homeRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/(home)/about': {
      id: '/(home)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeAboutImport
      parentRoute: typeof homeRouteImport
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexImport
      parentRoute: typeof homeRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/(home)/post/$postId': {
      id: '/(home)/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof homePostPostIdImport
      parentRoute: typeof homeRouteImport
    }
  }
}

// Create and export the route tree

interface homeRouteRouteChildren {
  homeAboutRoute: typeof homeAboutRoute
  homeIndexRoute: typeof homeIndexRoute
  homePostPostIdRoute: typeof homePostPostIdRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeAboutRoute: homeAboutRoute,
  homeIndexRoute: homeIndexRoute,
  homePostPostIdRoute: homePostPostIdRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof homeAboutRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/': typeof AuthIndexRoute
  '/post/$postId': typeof homePostPostIdRoute
}

export interface FileRoutesByTo {
  '/about': typeof homeAboutRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof homeIndexRoute
  '/auth': typeof AuthIndexRoute
  '/post/$postId': typeof homePostPostIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(home)': typeof homeRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(home)/about': typeof homeAboutRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/(home)/': typeof homeIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/(home)/post/$postId': typeof homePostPostIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/auth/confirm-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/'
    | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/auth/confirm-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/auth'
    | '/post/$postId'
  id:
    | '__root__'
    | '/(home)'
    | '/auth'
    | '/(home)/about'
    | '/auth/confirm-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/(home)/'
    | '/auth/'
    | '/(home)/post/$postId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(home)",
        "/auth"
      ]
    },
    "/(home)": {
      "filePath": "(home)/route.tsx",
      "children": [
        "/(home)/about",
        "/(home)/",
        "/(home)/post/$postId"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/confirm-email",
        "/auth/sign-in",
        "/auth/sign-up",
        "/auth/"
      ]
    },
    "/(home)/about": {
      "filePath": "(home)/about.tsx",
      "parent": "/(home)"
    },
    "/auth/confirm-email": {
      "filePath": "auth/confirm-email.tsx",
      "parent": "/auth"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx",
      "parent": "/auth"
    },
    "/(home)/": {
      "filePath": "(home)/index.tsx",
      "parent": "/(home)"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/(home)/post/$postId": {
      "filePath": "(home)/post/$postId.tsx",
      "parent": "/(home)"
    }
  }
}
ROUTE_MANIFEST_END */
